---
spring:
  main:
    web-application-type: reactive
    banner-mode: off
  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:25432/sws-test
    username: admin
    password: admin
  flyway:
    url: jdbc:postgresql://127.0.0.1:25432/sws-test
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    schemas: public
logging:
  level:
    root: info
